import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1CAAFA',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  overlayContent: {
    position:'absolute',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: '#fff',
    fontSize: 40,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    textAlign: 'center',
    left:60,
    marginTop: 150,
    marginBottom: 30, // Adicionando espaço abaixo do título
  },
  text: {
    color: '#fff',
    fontSize: 20,
    textShadowColor: '#000000BF',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
    marginBottom: 10, // Ajustando o espaçamento
   
  },
  textSelected: {
    color: '#000',
    fontSize: 20,
    textShadowColor: '#fff',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
   
  },
  formContainer: {
    flex: 1,
    left:60,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    textAlign:'left',
  },
  inputContainer: {
    flex:1,
    justifyContent: 'center',
    alignItems: 'flex-start', // Centraliza os inputs
    marginTop: 10,
    textAlign:'left',
  },
  input: {
    alignItems:'center',
    textAlign:'center',
    width: 300,
    height: 50,
    fontSize: 20,
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#1CAAFA',
    backgroundColor: '#fff',
    color: "black",
    marginBottom: 10, // Espaçamento entre inputs
  },
  inputSubmit: {
    height: 70,
    width: 300,
    paddingVertical: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334EA0',
    backgroundColor: '#334EA0',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50, // Espaçamento acima do botão
    left:60,
  },
  buttonText: {
    color: '#fff',
    fontSize: 25,
    textShadowColor: '#334EA0',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    padding: 35,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    width: 200,
    height: 'auto',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  backButton: {
    height: 50,
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    backgroundColor: '#334EA0',
    marginTop: 20,
  },
  backButtonText: {
    color: '#fff',
    fontSize: 18,
  },
  smallSquareButton: {
    position: 'absolute',
    top: 100,
    left: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#334EA0',
    borderRadius: 5,
  },
  smallSquareButtonText: {
    color: '#fff',
    fontSize: 18,
  },
  modalOption: {
    width: '100%',
    padding: 15,
    alignItems: 'center',
    borderRadius: 5,
    borderBottomWidth: 1,
    borderColor: '#ccc',
  },
  modalText: {
    fontSize: 16,
    color: '#000',
    textAlign: 'center',
  },
});
